//! Font DB: AGL, glyph maps, decoding through our own fonts, inference, builders.

pub mod build;

pub(crate) mod agl;
// Generated by a test in agl.rs, which also checks it is current.
#[rustfmt::skip]
mod agl_table;
pub(crate) mod decode;
pub(crate) mod gmap;
pub(crate) mod score;
pub(crate) mod template;
