#!/usr/bin/env python3
"""Writes THIRD_PARTY_CRATES.md: the licence of every crate the binary ships (T-35).

Run with an isolated interpreter from anywhere in the repo:

    python3 -I tools/crate-notices.py              # regenerate THIRD_PARTY_CRATES.md
    python3 -I tools/crate-notices.py --self-test  # the generator on synthetic input

The shipped graph is the normal dependencies of `pdfpundit` (default features) on
each of the three CI targets, merged. The authority for that set is
`cargo tree --locked -p pdfpundit -e normal --target <t>`, as in the purity gate:
cargo metadata's resolve keeps optional packages no build activates (it lists
termwiz, regex and 70 more that the binary never links). Build and dev
dependencies are not shipped and are left out. Name, version, licence and source
directory come from `cargo metadata --locked`; a crate cargo tree lists but
metadata lacks fails the run, so every shipped crate has a section.

Each section gives the SPDX licence expression, the targets that link the crate,
and the text of every licence or notice file at the root of its registry source
(`LICENSE*`, `LICENCE*`, `COPYING*`, `NOTICE*`; a directory of that name
contributes its files). A crate with none says so. The output is sorted and holds
no local path, so two runs over one Cargo.lock give the same bytes. CI regenerates
the file and fails on a diff.
"""

import json
import os
import subprocess
import sys

TARGETS = ["aarch64-apple-darwin", "x86_64-pc-windows-msvc", "x86_64-unknown-linux-gnu"]
ROOT_NAME = "pdfpundit"
PREFIXES = ("license", "licence", "copying", "notice")
OUTPUT = "THIRD_PARTY_CRATES.md"

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

HEADER = """\
# Third-party crates

Generated by `tools/crate-notices.py` from `Cargo.lock`; do not edit by hand.

The PDFPundit binary links the {count} crates below: the normal dependencies of
`pdfpundit` on {targets}.
Each section gives the crate's licence expression as its manifest declares it and
the text of the licence and notice files it ships.

PDFPundit's own licence is in `LICENSE`. Data compiled into the binary (fonts,
glyph lists, CMaps, ICC profiles, the DarkBerry palette) is covered by
`THIRD_PARTY_NOTICES.md`.
"""


def packages_by_key(meta):
    """{(name, version): package} for the registry packages in `meta`."""
    return {(p["name"], p["version"]): p for p in meta["packages"] if p["source"] is not None}


def notice_files(root):
    """[(relative name, text)] of the licence and notice files at a crate root."""
    out = []
    try:
        entries = sorted(os.listdir(root))
    except FileNotFoundError:
        raise SystemExit(f"crate-notices: no source at {root}; run `cargo fetch --locked`")
    for entry in entries:
        if not entry.lower().startswith(PREFIXES):
            continue
        path = os.path.join(root, entry)
        if os.path.isdir(path):
            for dirpath, dirs, files in os.walk(path):
                dirs.sort()
                for f in sorted(files):
                    full = os.path.join(dirpath, f)
                    rel = os.path.relpath(full, root).replace(os.sep, "/")
                    out.append((rel, read_text(full)))
        elif os.path.isfile(path):
            out.append((entry, read_text(path)))
    return out


def read_text(path):
    with open(path, "rb") as f:
        raw = f.read()
    text = raw.decode("utf-8", errors="replace").lstrip("﻿")
    lines = [line.rstrip() for line in text.replace("\r\n", "\n").replace("\r", "\n").split("\n")]
    return "\n".join(lines).strip("\n")


def fence(text):
    """A backtick fence longer than any backtick run in `text`."""
    longest = run = 0
    for ch in text:
        run = run + 1 if ch == "`" else 0
        longest = max(longest, run)
    return "`" * max(3, longest + 1)


def render(crates):
    """`crates`: [(name, version, licence or None, licence_file or None, [targets],
    [(file, text)])]. Returns the Markdown, sorted by name then version."""
    crates = sorted(crates, key=lambda c: (c[0], version_key(c[1])))
    out = [HEADER.format(count=len(crates), targets=", ".join(f"`{t}`" for t in TARGETS))]
    out.append("| Crate | Version | Licence | Targets |\n|---|---|---|---|")
    for name, version, licence, _, targets, _ in crates:
        out.append(f"| {name} | {version} | {licence_label(licence)} | {target_label(targets)} |")
    out.append("")
    for name, version, licence, licence_file, targets, files in crates:
        out.append(f"## {name} {version}\n")
        out.append(f"- Licence: {licence_label(licence)}")
        if licence_file:
            out.append(f"- Licence file named in the manifest: `{licence_file}`")
        out.append(f"- Targets: {target_label(targets)}")
        out.append("")
        if not files:
            out.append(f"The crate ships no licence or notice file; its manifest declares "
                       f"{licence_label(licence)}.\n")
        for fname, text in files:
            f = fence(text)
            out.append(f"### `{fname}`\n\n{f}text\n{text}\n{f}\n")
    return "\n".join(out).rstrip("\n") + "\n"


def licence_label(licence):
    return f"`{licence}`" if licence else "none declared"


def target_label(targets):
    return "all" if sorted(targets) == sorted(TARGETS) else ", ".join(sorted(targets))


def version_key(version):
    core = version.split("+")[0].split("-")[0]
    return tuple(int(p) if p.isdigit() else 0 for p in core.split(".")), version


def cargo(*args):
    return subprocess.check_output(["cargo", *args], cwd=REPO, text=True)


def tree_set(target):
    return parse_tree(cargo("tree", "--locked", "-p", ROOT_NAME, "--target", target,
                            "-e", "normal", "--prefix", "none", "--no-dedupe", "-f", "{p}"))


def parse_tree(out):
    """{(name, version)} from `cargo tree --prefix none -f {p}`, the root left out."""
    seen = set()
    for line in out.splitlines():
        parts = line.split()
        if len(parts) >= 2 and parts[1].startswith("v") and parts[0] != ROOT_NAME:
            seen.add((parts[0], parts[1][1:]))
    return seen


def generate():
    meta = json.loads(cargo("metadata", "--locked", "--format-version", "1"))
    packages = packages_by_key(meta)
    targets_of = {}
    for target in TARGETS:
        for key in tree_set(target):
            targets_of.setdefault(key, []).append(target)
    missing = sorted(k for k in targets_of if k not in packages)
    if missing:
        raise SystemExit(f"crate-notices: cargo tree lists crates cargo metadata lacks: {missing}")
    crates = []
    for key in sorted(targets_of):
        pkg = packages[key]
        root = os.path.dirname(pkg["manifest_path"])
        crates.append((pkg["name"], pkg["version"], pkg.get("license"),
                       pkg.get("license_file"), targets_of[key], notice_files(root)))
    return render(crates)


def write():
    text = generate()
    with open(os.path.join(REPO, OUTPUT), "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    count = text.count("\n## ")
    print(f"{OUTPUT}: {count} crates")
    return 0


def self_test():
    failures = []

    def check(what, got, want):
        if got != want:
            failures.append(f"{what}: got {got!r}, want {want!r}")

    tree = ("pdfpundit v0.1.0 (/src/pdfpundit)\nserde v1.0.229\n"
            "serde_derive v1.0.229 (proc-macro)\n\nserde v1.0.229\nwindows-sys v0.61.2\n")
    check("cargo tree parse: root dropped, proc-macros kept, duplicates merged",
          sorted(parse_tree(tree)),
          [("serde", "1.0.229"), ("serde_derive", "1.0.229"), ("windows-sys", "0.61.2")])
    meta = {"packages": [
        {"name": "pdfpundit", "version": "0.1.0", "source": None},
        {"name": "serde", "version": "1.0.229", "source": "registry+https://x"},
    ]}
    check("path packages are not third-party", sorted(packages_by_key(meta)),
          [("serde", "1.0.229")])

    check("fence over a triple-backtick text", fence("x ``` y"), "````")
    check("fence over plain text", fence("plain"), "```")
    check("version order is numeric", sorted(["0.10.0", "0.9.1", "0.9.10"], key=version_key),
          ["0.9.1", "0.9.10", "0.10.0"])

    crates = [
        ("zeta", "1.0.0", "MIT", None, list(TARGETS), [("LICENSE", "zeta licence")]),
        ("alpha", "0.10.0", None, None, ["x86_64-pc-windows-msvc"], []),
        ("alpha", "0.9.0", "Apache-2.0", "LICENSE.txt", list(TARGETS),
         [("LICENSE-APACHE", "uses ``` inside")]),
    ]
    a = render(crates)
    b = render(list(reversed(crates)))
    check("render is order-independent", a == b, True)
    sections = [line for line in a.splitlines() if line.startswith("## ")]
    check("sections sorted by name then version", sections,
          ["## alpha 0.9.0", "## alpha 0.10.0", "## zeta 1.0.0"])
    check("a crate with no file says so",
          "The crate ships no licence or notice file; its manifest declares none declared." in a,
          True)
    check("a fenced text with backticks gets a longer fence", "````text\nuses ``` inside\n````" in a,
          True)
    check("per-target crates name their target", "| alpha | 0.10.0 | none declared | "
          "x86_64-pc-windows-msvc |" in a, True)
    check("output ends with one newline", a.endswith("\n") and not a.endswith("\n\n"), True)

    import tempfile
    with tempfile.TemporaryDirectory() as d:
        for rel, body in [("LICENSE-MIT", "mit\r\nline  \r\n"), ("COPYING", "﻿copying"),
                          ("LICENSES/Apache-2.0.txt", "apache"), ("README.md", "no"),
                          ("src/LICENSE", "nested, not at root"), ("NOTICE", "notice")]:
            path = os.path.join(d, *rel.split("/"))
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8", newline="") as f:
                f.write(body)
        check("notice files at the root, directories expanded, text normalised", notice_files(d),
              [("COPYING", "copying"), ("LICENSE-MIT", "mit\nline"),
               ("LICENSES/Apache-2.0.txt", "apache"), ("NOTICE", "notice")])

    for f in failures:
        print(f"self-test FAIL: {f}")
    print(f"self-test: {len(failures)} failures")
    return 1 if failures else 0


def main(argv):
    if argv == ["--self-test"]:
        return self_test()
    if argv:
        print(__doc__)
        return 2
    return write()


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
