#!/usr/bin/env python3
"""Regenerate the human-readable Markdown views from the JSONL registries (never hand-edit them).

    python research/tools/render_views.py

Writes gaps/register.md, sources/index.md, tooling/ledger.md, damage/classes.md,
hypotheses/index.md. Gap priority = 0.4*impact + 0.2*(novelty + feasibility + confidence).
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from kbcommon import REGISTRIES, ROOT, load_jsonl  # noqa: E402

HEADER = "<!-- GENERATED by research/tools/render_views.py from {src} — do not edit by hand -->\n\n"


def cell(v) -> str:
    if v is None:
        return ""
    if isinstance(v, list):
        v = ", ".join(str(x) for x in v)
    return str(v).replace("|", "\\|").replace("\n", " ")


def table(rows: list[list], head: list[str]) -> str:
    out = ["| " + " | ".join(head) + " |", "|" + "---|" * len(head)]
    out += ["| " + " | ".join(cell(c) for c in r) + " |" for r in rows]
    return "\n".join(out) + "\n"


def priority(g: dict) -> float:
    s = g["scores"]
    return round(0.4 * s["impact"] + 0.2 * (s["novelty"] + s["feasibility"] + s["confidence"]), 2)


def main() -> None:
    R = {t: load_jsonl(p) for t, (p, _, _) in REGISTRIES.items()}
    claims = {c["id"]: c for c in R["claim"]}

    gaps = sorted(R["gap"], key=lambda g: (-priority(g), g["id"]))
    verified = lambda g: sum(claims.get(c, {}).get("quote_check") in ("exact", "fuzzy") for c in g["evidence"])  # noqa: E731
    body = "# Gap register\n\nSorted by priority. `ev` = evidence claims (verified quotes / total).\n\n"
    body += table([[g["id"], priority(g), g["title"], g["type"], g["status"], g["still_open"],
                    f"{verified(g)}/{len(g['evidence'])}", g.get("workstream"), g.get("damage_classes", []),
                    g.get("hypotheses", [])] for g in gaps],
                  ["id", "prio", "title", "type", "status", "open?", "ev", "ws", "damage", "hyp"])
    body += "\n## Statements\n\n" + "".join(
        f"### {g['id']} — {g['title']}\n\n{g['statement']}\n\n"
        + (f"*Inference:* {g['inference']}\n\n" if g.get("inference") else "")
        + "Evidence: " + ", ".join(f"{c} ({claims.get(c, {}).get('src', '?')}, "
                                   f"{claims.get(c, {}).get('quote_check', '?')})" for c in g["evidence"]) + "\n\n"
        for g in gaps)
    (ROOT / "gaps" / "register.md").write_text(HEADER.format(src="gaps/gaps.jsonl") + body)

    srcs = sorted(R["source"], key=lambda s: s["id"])
    body = "# Source index\n\n" + table(
        [[s["id"], s["title"], s.get("year"), s.get("venue"), s["status"], s.get("relevance"),
          s.get("access"), "yes" if s.get("fulltext_sha256") else "", s.get("doi_check", ""),
          s.get("topics", [])] for s in srcs],
        ["id", "title", "year", "venue", "status", "rel", "access", "fulltext", "doi", "topics"])
    (ROOT / "sources" / "index.md").write_text(HEADER.format(src="sources/registry.jsonl") + body)

    order = {"Adopt": 0, "Trial": 1, "Assess": 2, "Hold": 3}
    tools = sorted(R["tool"], key=lambda t: (order[t["verdict"]], t["category"], t["name"]))
    body = "# Tooling ledger\n\nVerdicts: **Adopt** use now · **Trial** use in a bounded experiment · " \
           "**Assess** worth a look · **Hold** don't use (reason given).\n\n" + table(
        [[t["id"], t["name"], t["verdict"], t["category"], t["purpose"], t.get("verified_in_container"),
          t.get("version"), t.get("license"), t.get("cost"), t.get("keys_required"), t["checked_at"]] for t in tools],
        ["id", "name", "verdict", "category", "purpose", "verified", "version", "license", "cost", "keys", "checked"])
    body += "\n## Rationale\n\n" + "".join(
        f"- **{t['id']} {t['name']}** ({t['verdict']}): {t.get('rationale') or ''}"
        + (f" Evidence: {t['verification_evidence']}" if t.get("verification_evidence") else "") + "\n" for t in tools)
    (ROOT / "tooling" / "ledger.md").write_text(HEADER.format(src="tooling/ledger.jsonl") + body)

    body = "# Damage classes (beyond REPDF C1–C10)\n\n" + "".join(
        f"## {d['id']} — {d['name']} ({d['status']})\n\n{d['description']}\n\n"
        f"- Maps to: {cell(d.get('maps_to', [])) or '—'}\n- Generator: {d['generator_spec']}\n"
        f"- Realism: {d['realism']}\n- Evidence: {cell(d.get('evidence', [])) or '—'}\n\n"
        for d in sorted(R["damage"], key=lambda d: d["id"]))
    (ROOT / "damage" / "classes.md").write_text(HEADER.format(src="damage/classes.jsonl") + body)

    body = "# Hypotheses\n\n" + table(
        [[h["id"], h["status"], h["statement"], h["metric"], h.get("gaps", []),
          "".join("Y" if h["readiness"][k] else "n" for k in
                  ("measurable", "data_reachable", "baselines_verified", "verified_gap"))] for h in
         sorted(R["hypothesis"], key=lambda h: h["id"])],
        ["id", "status", "statement", "metric", "gaps", "ready (M/D/B/G)"])
    (ROOT / "hypotheses" / "index.md").write_text(HEADER.format(src="hypotheses/hypotheses.jsonl") + body)
    print("views rendered")


if __name__ == "__main__":
    main()
